= d3-resolve(1)
András Bodor <bodand@proton.me>
v0.1.0
:doctype: manpage

== NAME

d3-resolve - Resolve current IP address and pass it forward

== SYNOPSIS

*d3-resolve* [-46bhv] _exec..._

== OPTIONS

*-4*::
Look up the currrent IPv4 address. (On by default if nothing present.)

*-6*::
Look up the current IPv6 address. (Off by default if nothing present.)

*-b* _backend_::
The backend to use to figure out the current IP address.

*-h*::
Print help information and exit.

*-v*::
Print version information and exit.


== ARGUMENTS

_exec..._::
The executable program and arguments that the current process is to exec into.
The _exec_ process will have the resolved IP addresses line-by-line available on their STDIN.
If not given, resolved addresses are printed on the current process's STDOUT and *d3-resolve* exits with 2.

== DESCRIPTION

The *d3-resolve* program looks up what the current system's public IP address
is.  By default it tries to look up and IPv4 address but this can be changed to
look up only one or both of IPv4 and IPv6 using one or both of the *-4* or *-6*
flags.  If this fails, it exits with exit code 1.

The method of lookup is dependent on the backend used.  After successfully
performing the resolving of the IP address(es) *d3-resolve* *exec(2)*s into its
_exec..._ argument line.  If you'd like a custom solution to look up your IP,
feel free to contribute your code to do so.

After successfully performing the resolving of the IP address(es) *d3-resolve*
*exec(2)s* into its _exec..._ argument line.  Before this execution, the
resolved address(as) are written to the STDIN of the child process.  If no
arguments are passed as _exec..._, the address(es) are printed to STDOUT and
*d3-resolve* exits with exit code 2.

[#backends]
=== Backends

Currently the following backends are supported.

https://www.ipify.org/[ipify]:: 
Use the ipify website's API to query for the current IP address.

== EXIT CODES

*1*:: Could not reach the given IP resolver.
Additional information, if available, is printed to STDERR.

*2*:: Incorrect usage.
Additional information is available on STDERR.

*3*:: Could not execute into present exec parameters.
Error message from the system is available on STDERR.

== SEE ALSO

*d3-filter(1)*::
Perform filtering on an input stream of IP addresses and domain names.

*d3-update(1)*::
Update a given DNS record at the provided DNS provider.

*d3-query(1)*::
Perform DNS A and AAAA record lookups.

== COPYING

Copyright (c) 2025 {author} <{email}> +
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
	list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
	this list of conditions and the following disclaimer in the documentation
	and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

